name: Deploy Stack to AWS CloudFormation

on:
  push:
    paths:
      - 'benwaddell-com.yaml'

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
    - uses: aws-actions/aws-cloudformation-github-deploy@v1.0.3
      with:
        name: benwaddell-com
        template: benwaddell-com.yaml